# Generated by Django 3.1.4 on 2020-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forexAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='time',
            field=models.DateField(),
        ),
    ]
